name: Build - Server

on:
  push:
    branches:
      - master

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/application-build.yaml@main
    with:
      application-name: online_bank
    secrets: inherit
